---
linters-settings:
#  lll:
#    line-length: 140
#    tab-width: 4

  unused:
    check-exported: true

  unparam:
    check-exported: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
#    - dupl
#    - errcheck
    - exportloopref
    - exhaustive
#    - funlen
#    - gochecknoinits
#    - goconst
#    - gocritic
#    - gocyclo
    - gofmt
    - goimports
    - revive
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
#    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
#    - rowserrcheck
    - staticcheck
    - structcheck
#    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

issues:
  exclude-use-default: false
  exclude:
    # gas: Duplicated errcheck checks
    - 'G104: Errors unhandled'
    - 'ST1000: at least one file in a package should have a package comment'
    - 'mnd: Magic number'
    - 'use underscores in Go names'
    - 'Error return value of `.+` is not checked'
    - 'Unhandled error'
    - 'var `.+` should be `.+`'
    - 'a blank import should be only in a main or test package'
    - 'exported .+ should have comment'
    - 'var-naming'
